language: go

go:
        - 1.7

branches:
        only: master

before_install:
        - go get -t -v ./...
        - go get -v github.com/mitchellh/gox
        - go get -v github.com/tcnksm/ghr
        - go get golang.org/x/tools/cmd/cover
        - sudo pip install codecov

script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
        - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -ldflags="-X main.apikey=$SECRET_KEY"
        - sh scripts/package.sh
        - ghr --username syui --token $GITHUB_TOKEN 0.1 dist/
        - codecov
